### ISSUE TITLE
Recent TCP drain logic fails if optional field `health_check_http` is not configured

### ISSUE THREAD

**Issue by davidlohle** [cloudfoundry/haproxy-boshrelease#788]
Hi there!

I recently upgraded to the 14.6.0+2.8.13 release and noticed on what I believe to be a small bug.

I have a TCP backend configured with the following YAML:

```
    tcp:
      - name: diego_brain
        port: 2222
        backend_servers: ((DIEGO_BRAIN_SERVERS))
 ```

Once 14.6.0+2.8.13 is applied, any subsequent changes result in a failed deploy due to failed HAProxy drain scripts.

Looking into the matter, I believe the issue lies in my lack of an `health_check_http` value, though this is considered an optional key.

The `haproxy.conf.erb` template checks for the tcp[X].health_check_http here: [haproxy.config.erb:1038](https://github.com/sap-contributions/haproxy-boshrelease/blob/6dc3b8df4646cc7934023737815a375dd4be61e2/jobs/haproxy/templates/haproxy.config.erb#L1038) to determine whether or not to add the configuration lines. 

However, the drain script does not check for the presence of this key. It assumes that if you have the `tcp` key, it will attempt to shut down the HTTP health check: [drain.erb:65](https://github.com/sap-contributions/haproxy-boshrelease/blob/6dc3b8df4646cc7934023737815a375dd4be61e2/jobs/haproxy/templates/drain.erb#L65)

This attempt to disable a frontend that isn't running results in the drain script failing, and the bosh deploy failing as well.

If I update the config to say:
```
    tcp:
      - name: diego_brain
        port: 2222
        backend_servers: ((DIEGO_BRAIN_SERVERS))
        health_check_http: 5555
 ```

All future changes succeed. However, I do not want an HTTP health check endpoint exposed, and would like to keep this disabled. 

I believe we should check for the presence of the `health_check_http` value before appending the socat statement, like so:

```
<%- tcp.each do |tcp_proxy| -%>
  <%- if tcp_proxy.health_check_http -%>
  echo "disable frontend health_check_http_tcp-<%= tcp_proxy["name"] %>" | /usr/local/bin/socat stdio unix-connect:${sockfile}
  <%- end -%>
<%- end -%>
```

I hope my assessment is correct. I have tried this in a few environments and found success—but I don't rule out PEBKAC :) Thank you very much for this release, and please let me know if there's anything I can help with.
